name: CI - Release (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./sevenwiki-desktop/

      - name: Build the Tauri app
        run: npm run build
        working-directory: ./sevenwiki-desktop/

      - name: Compress .app folder
        run: |
          cd ./sevenwiki-desktop/src-tauri/target/release/bundle/macos/
          zip -r app.zip *.app

      - name: Upload build artifacts (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-macos
          path: |
            ./sevenwiki-desktop/src-tauri/target/release/bundle/macos/app.zip
            ./sevenwiki-desktop/src-tauri/target/release/bundle/dmg/*.dmg

      - name: Result
        run: echo "Build completed on ${{ runner.os }}"
        working-directory: ./sevenwiki-desktop/
